In [ ]:
#preparing new cases from My world in Data for mpox in subsampled countries

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/Users/mparedes/Downloads/owid-monkeypox-data.csv") # from https://ourworldindata.org/explorers/monkeypox

In [5]:
df

,location,iso_code,date,total_cases,total_deaths,new_cases,new_deaths,new_cases_smoothed,new_deaths_smoothed,new_cases_per_million,total_cases_per_million,new_cases_smoothed_per_million,new_deaths_per_million,total_deaths_per_million,new_deaths_smoothed_per_million
0,Andorra,AND,2022-07-25,2.0,0.0,2.0,0.0,0.29,0.00,25.049,25.049,3.632,0.000,0.000,0.0
1,Andorra,AND,2022-07-26,3.0,0.0,1.0,0.0,0.43,0.00,12.525,37.574,5.386,0.000,0.000,0.0
2,Andorra,AND,2022-07-27,3.0,0.0,0.0,0.0,0.43,0.00,0.000,37.574,5.386,0.000,0.000,0.0
3,Andorra,AND,2022-07-28,3.0,0.0,0.0,0.0,0.43,0.00,0.000,37.574,5.386,0.000,0.000,0.0
4,Andorra,AND,2022-07-29,3.0,0.0,0.0,0.0,0.43,0.00,0.000,37.574,5.386,0.000,0.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17413,World,OWID_WRL,2022-12-19,83038.0,67.0,144.0,1.0,58.57,0.29,0.018,10.412,0.007,0.000,0.008,0.0
17414,World,OWID_WRL,2022-12-20,83175.0,67.0,137.0,0.0,67.86,0.29,0.017,10.429,0.009,0.000,0.008,0.0
17415,World,OWID_WRL,2022-12-21,83339.0,72.0,164.0,5.0,77.57,1.00,0.021,10.450,0.010,0.001,0.009,0.0
17416,World,OWID_WRL,2022-12-22,83420.0,72.0,81.0,0.0,84.57,1.00,0.010,10.460,0.011,0.000,0.009,0.0
17417,World,OWID_WRL,2022-12-23,83497.0,72.0,77.0,0.0,91.86,1.00,0.010,10.470,0.012,0.000,0.009,0.0

In [6]:
#the only countries with enough sequences (>5)
countries = ["Austria",
"Belgium",
"Canada",
"Colombia",
"France",
"Germany",
"Italy",
"Netherlands",
"Peru",
"Portugal",
"Slovakia",
"Slovenia",
"Spain",
"Switzerland",
"United States",
"United Kingdom",
]

In [11]:
df = df[df.location.isin(countries)]
df = df[["location", "date", "new_cases_smoothed"]]
df

In [22]:
#wide format for easy beauti input
wide_df = pd.pivot(df, index="location", columns="date", values="new_cases_smoothed")
wide_df = wide_df.replace(np.nan, 0.001)
wide_df = wide_df.replace(0.00, 0.001) #can't have 0 values for log standarization
wide_df

date,2022-05-07,2022-05-08,2022-05-09,2022-05-10,2022-05-11,2022-05-12,2022-05-13,2022-05-14,2022-05-15,2022-05-16,...,2022-12-14,2022-12-15,2022-12-16,2022-12-17,2022-12-18,2022-12-19,2022-12-20,2022-12-21,2022-12-22,2022-12-23
location,,,,,,,,,,,,,,,,,,,,,
Austria,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001
Belgium,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001
Canada,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001
Colombia,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,4.000,4.000,4.000,4.000,4.000,4.000,0.001,9.000,9.000,9.000
France,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001
Germany,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.290,0.290,0.290,0.290,0.290,0.290,0.140,0.001,0.001,0.001
Italy,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.570,0.570,0.710,0.710,0.710,0.710,1.290,0.001,0.001,0.001
Netherlands,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.570,0.570,0.710,0.710,0.710,0.710,0.140,0.001,0.001,0.001
Peru,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,8.290,0.710,0.710,3.000,3.000,3.000,5.430,8.000,8.000,9.000
Portugal,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001
Slovakia,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001
Slovenia,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001
Spain,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,1.140,1.140,0.570,0.570,0.570,0.570,11.430,0.001,0.001,0.001
Switzerland,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001
United Kingdom,0.140,0.140,0.140,0.140,0.140,0.140,0.140,0.290,0.290,0.860,...,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001
United States,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,11.570,0.001,0.001,0.001,0.001,0.001,0.001,2.140,2.140,4.140

In [25]:
rev_wide = wide_df[wide_df.columns[::-1]]

In [26]:
rev_wide.to_csv("../mascot_glm/data/ne_case_pred.csv")