In [17]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv("../monkeypox-build/data/nextstrain__metadata_1000.tsv", sep = "\t")

In [19]:
df

,strain,date,host,recency,lineage,date_submitted,country,clade_membership,region,author,accession,GA_CT_fraction,dinuc_context_fraction
0,4061,2022-05-20,Homo sapiens,Older,B.1,2022-06-24,Spain,IIb,Europe,"de la Hoz-Sanchez,B., Lopez-Ortiz,M., Gutierre...",ON838940,NaN,NaN
1,8887,2022-06-06,Homo sapiens,Older,B.1,2022-06-24,Spain,IIb,Europe,"de la Hoz-Sanchez,B., Lopez-Ortiz,M., Gutierre...",ON838939,NaN,NaN
2,9000231,2022-07-31,Homo sapiens,Older,B.1.2,2022-09-12,United Kingdom,IIb,Europe,"Groves,N., Osman,K.L., Lewandowski,K.S., Carte...",OP413713,0.83,0.8
3,9000289,2022-08-01,Homo sapiens,Older,B.1.7,2022-09-12,United Kingdom,IIb,Europe,"Groves,N., Osman,K.L., Lewandowski,K.S., Carte...",OP413714,1.00,1.0
4,9000369,2022-08-01,Homo sapiens,Older,B.1.2,2022-09-27,United Kingdom,IIb,Europe,"Groves,N., Osman,K.L., Lewandowski,K.S., Carte...",OP536750,1.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1071,Monkeypox virus/Human/USA/CA-LACPHL-MA00379/2022,2022-10-12,Homo sapiens,3-7 days ago,B.1.2,2023-01-26,USA,IIb,North America,"Hemarajata,P., Green,N.M., Garrigues,J.M.",OQ330985,1.00,1.0
1072,MPXV_USA_2022_AZ0007,2022-09-11,Homo sapiens,Older,B.1.2,2022-12-15,USA,IIb,North America,"Gigante,C., Francis,D., Zhao,H., Batra,D., Het...",OQ054243,NaN,NaN
1073,MPXV/Human/USA/CA-LACPHL-MA00288/2022,2022-10-04,Homo sapiens,Older,B.1.2,2022-11-24,USA,IIb,North America,"Hemarajata,P., Green,N.M., Garrigues,J.M.",OP890546,1.00,1.0
1074,B1221120,2022-11-09,Homo sapiens,Older,B.1.2,2022-12-02,USA,IIb,North America,"Bajwa,M.I., Miller,H.",OP935997,NaN,NaN
1075,B1221119,2022-11-08,Homo sapiens,Older,B.1.2,2022-12-02,USA,IIb,North America,"Bajwa,M.I., Miller,H.",OP935996,1.00,1.0

In [20]:
north_america = ['Canada','USA']
western_europe = ['Austria','Germany','Switzerland','United Kingdom','France','Belgium']
central_europe = ['Slovakia','Slovenia']
southern_europe = ['Italy','Portugal','Spain']
south_american = ['Colombia','Peru']

In [21]:
df["region_coarse"] = np.nan
df.region_coarse[df.country.isin(north_america)] = "North America"
df['region_coarse'][df.country.isin(western_europe)] = "Western Europe"
df['region_coarse'][df.country.isin(central_europe)] = "Central Europe"
df['region_coarse'][df.country.isin(southern_europe)] = "Southern Europe"
df['region_coarse'][df.country.isin(south_american)] = "South America"

/var/folders/h9/0347drb57tsgxzbddmvmlvf80000gp/T/ipykernel_11344/557305204.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.region_coarse[df.country.isin(north_america)] = "North America"

In [22]:
df = df[["accession", "date", "region_coarse", "country", "strain"]]
df

,accession,date,region_coarse,country,strain
0,ON838940,2022-05-20,Southern Europe,Spain,4061
1,ON838939,2022-06-06,Southern Europe,Spain,8887
2,OP413713,2022-07-31,Western Europe,United Kingdom,9000231
3,OP413714,2022-08-01,Western Europe,United Kingdom,9000289
4,OP536750,2022-08-01,Western Europe,United Kingdom,9000369
...,...,...,...,...,...
1071,OQ330985,2022-10-12,North America,USA,Monkeypox virus/Human/USA/CA-LACPHL-MA00379/2022
1072,OQ054243,2022-09-11,North America,USA,MPXV_USA_2022_AZ0007
1073,OP890546,2022-10-04,North America,USA,MPXV/Human/USA/CA-LACPHL-MA00288/2022
1074,OP935997,2022-11-09,North America,USA,B1221120
1075,OP935996,2022-11-08,North America,USA,B1221119

In [23]:
df.to_csv("../monkeypox-build/data/metadata_region_1000.tsv", sep = "\t")